// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBanGiay.Repositoty;

#nullable disable

namespace WebBanGiay.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241111031723_sdsssss")]
    partial class sdsssss
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebBanGiay.Models.ChiTietDonHangModel", b =>
                {
                    b.Property<int>("ID_CHI_TIET_DON_HANG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_CHI_TIET_DON_HANG"), 1L, 1);

                    b.Property<decimal>("GIA_BAN")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ID_DON_HANG")
                        .HasColumnType("int");

                    b.Property<int>("ID_SAN_PHAM")
                        .HasColumnType("int");

                    b.Property<string>("MauSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SO_LUONG")
                        .HasColumnType("int");

                    b.Property<decimal>("THANH_TIEN")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID_CHI_TIET_DON_HANG");

                    b.HasIndex("ID_DON_HANG");

                    b.HasIndex("ID_SAN_PHAM");

                    b.ToTable("CHI_TIET_DON_HANGs");
                });

            modelBuilder.Entity("WebBanGiay.Models.DonHangModel", b =>
                {
                    b.Property<int>("ID_DON_HANG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_DON_HANG"), 1L, 1);

                    b.Property<string>("DIACHI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhThucThanhToan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ID_NGUOI_DUNG")
                        .HasColumnType("int");

                    b.Property<int?>("ID_NHAN_VIEN")
                        .HasColumnType("int");

                    b.Property<string>("LY_DO_HUY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NGAY_DAT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NGAY_GIAO")
                        .HasColumnType("datetime2");

                    b.Property<string>("TEN_NGUOI_NHAN")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("TRANG_THAI_DH")
                        .HasColumnType("int");

                    b.Property<string>("TRANG_THAI_THANH_TOAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_DON_HANG");

                    b.HasIndex("ID_NGUOI_DUNG");

                    b.HasIndex("ID_NHAN_VIEN");

                    b.ToTable("DON_HANGs");
                });

            modelBuilder.Entity("WebBanGiay.Models.GioHangModel", b =>
                {
                    b.Property<int>("ID_GIO_HANG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_GIO_HANG"), 1L, 1);

                    b.Property<decimal>("GIA_BAN")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ID_NGUOI_DUNG")
                        .HasColumnType("int");

                    b.Property<int>("ID_SAN_PHAM")
                        .HasColumnType("int");

                    b.Property<string>("MAU_SP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SO_LUONG_GH")
                        .HasColumnType("int");

                    b.Property<decimal>("THANH_TIEN")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TRANG_THAI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_GIO_HANG");

                    b.HasIndex("ID_NGUOI_DUNG");

                    b.HasIndex("ID_SAN_PHAM");

                    b.ToTable("GIO_HANGs");
                });

            modelBuilder.Entity("WebBanGiay.Models.HinhAnhModel", b =>
                {
                    b.Property<int>("ID_HINH_ANH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_HINH_ANH"), 1L, 1);

                    b.Property<int>("ID_SAN_PHAM")
                        .HasColumnType("int");

                    b.Property<string>("TEN_HINH_ANH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_HINH_ANH");

                    b.HasIndex("ID_SAN_PHAM");

                    b.ToTable("HINH_ANHs");
                });

            modelBuilder.Entity("WebBanGiay.Models.KichThuocSanPhamModel", b =>
                {
                    b.Property<int>("ID_KICH_THUOC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_KICH_THUOC"), 1L, 1);

                    b.Property<int>("TEN_KICH_THUOC")
                        .HasColumnType("int");

                    b.HasKey("ID_KICH_THUOC");

                    b.ToTable("KICH_THUOCs");
                });

            modelBuilder.Entity("WebBanGiay.Models.LoaiSanPhamModel", b =>
                {
                    b.Property<int>("ID_LOAI")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_LOAI"), 1L, 1);

                    b.Property<string>("TEN_LOAI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_LOAI");

                    b.ToTable("LOAI_SAN_PHAMs");
                });

            modelBuilder.Entity("WebBanGiay.Models.MauSanPhamModel", b =>
                {
                    b.Property<int>("ID_MAU")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_MAU"), 1L, 1);

                    b.Property<string>("TEN_MAU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_MAU");

                    b.ToTable("MauSanPhamModel");
                });

            modelBuilder.Entity("WebBanGiay.Models.NguoiDungModel", b =>
                {
                    b.Property<int>("ID_NGUOI_DUNG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_NGUOI_DUNG"), 1L, 1);

                    b.Property<string>("AccessToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DIA_CHI")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GTTT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HINH_ANH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HO_TEN")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("MAT_KHAU")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("NGAY_TAO")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TAI_KHOAN")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("TRANG_THAI")
                        .HasColumnType("int");

                    b.Property<int>("VAI_TRO")
                        .HasColumnType("int");

                    b.HasKey("ID_NGUOI_DUNG");

                    b.ToTable("NGUOI_DUNGs");
                });

            modelBuilder.Entity("WebBanGiay.Models.SanPhamMauModel", b =>
                {
                    b.Property<int>("ID_MauSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_MauSanPham"), 1L, 1);

                    b.Property<int>("ID_MAU")
                        .HasColumnType("int");

                    b.Property<int>("ID_SAN_PHAM")
                        .HasColumnType("int");

                    b.HasKey("ID_MauSanPham");

                    b.HasIndex("ID_MAU");

                    b.HasIndex("ID_SAN_PHAM");

                    b.ToTable("SAN_PHAM_MAUs");
                });

            modelBuilder.Entity("WebBanGiay.Models.SanPhamModel", b =>
                {
                    b.Property<int>("ID_SAN_PHAM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_SAN_PHAM"), 1L, 1);

                    b.Property<string>("CHAT_LIEU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GIA_BAN")
                        .HasColumnType("int");

                    b.Property<int>("GIA_NHAP")
                        .HasColumnType("int");

                    b.Property<int>("ID_KICH_THUOC")
                        .HasColumnType("int");

                    b.Property<int>("ID_LOAI")
                        .HasColumnType("int");

                    b.Property<string>("MO_TA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NGAY_TAO")
                        .HasColumnType("datetime2");

                    b.Property<int>("SO_LUONG")
                        .HasColumnType("int");

                    b.Property<string>("TEN_SAN_PHAM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_SAN_PHAM");

                    b.HasIndex("ID_KICH_THUOC");

                    b.HasIndex("ID_LOAI");

                    b.ToTable("SAN_PHAMs");
                });

            modelBuilder.Entity("WebBanGiay.Models.ChiTietDonHangModel", b =>
                {
                    b.HasOne("WebBanGiay.Models.DonHangModel", "DON_HANG")
                        .WithMany("CHI_TIET_DON_HANG")
                        .HasForeignKey("ID_DON_HANG")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebBanGiay.Models.SanPhamModel", "SAN_PHAM")
                        .WithMany()
                        .HasForeignKey("ID_SAN_PHAM")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DON_HANG");

                    b.Navigation("SAN_PHAM");
                });

            modelBuilder.Entity("WebBanGiay.Models.DonHangModel", b =>
                {
                    b.HasOne("WebBanGiay.Models.NguoiDungModel", "NGUOI_DUNG")
                        .WithMany()
                        .HasForeignKey("ID_NGUOI_DUNG")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebBanGiay.Models.NguoiDungModel", "NHAN_VIEN")
                        .WithMany()
                        .HasForeignKey("ID_NHAN_VIEN");

                    b.Navigation("NGUOI_DUNG");

                    b.Navigation("NHAN_VIEN");
                });

            modelBuilder.Entity("WebBanGiay.Models.GioHangModel", b =>
                {
                    b.HasOne("WebBanGiay.Models.NguoiDungModel", "NGUOI_DUNG")
                        .WithMany()
                        .HasForeignKey("ID_NGUOI_DUNG")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebBanGiay.Models.SanPhamModel", "SAN_PHAM")
                        .WithMany()
                        .HasForeignKey("ID_SAN_PHAM")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NGUOI_DUNG");

                    b.Navigation("SAN_PHAM");
                });

            modelBuilder.Entity("WebBanGiay.Models.HinhAnhModel", b =>
                {
                    b.HasOne("WebBanGiay.Models.SanPhamModel", "SAN_PHAM")
                        .WithMany("HINH_ANH")
                        .HasForeignKey("ID_SAN_PHAM")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SAN_PHAM");
                });

            modelBuilder.Entity("WebBanGiay.Models.SanPhamMauModel", b =>
                {
                    b.HasOne("WebBanGiay.Models.MauSanPhamModel", "Mau")
                        .WithMany()
                        .HasForeignKey("ID_MAU")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebBanGiay.Models.SanPhamModel", "SanPham")
                        .WithMany("SanPhamMau")
                        .HasForeignKey("ID_SAN_PHAM")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mau");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("WebBanGiay.Models.SanPhamModel", b =>
                {
                    b.HasOne("WebBanGiay.Models.KichThuocSanPhamModel", "TEN_KICH_THUOC")
                        .WithMany()
                        .HasForeignKey("ID_KICH_THUOC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebBanGiay.Models.LoaiSanPhamModel", "TEN_LOAI")
                        .WithMany()
                        .HasForeignKey("ID_LOAI")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TEN_KICH_THUOC");

                    b.Navigation("TEN_LOAI");
                });

            modelBuilder.Entity("WebBanGiay.Models.DonHangModel", b =>
                {
                    b.Navigation("CHI_TIET_DON_HANG");
                });

            modelBuilder.Entity("WebBanGiay.Models.SanPhamModel", b =>
                {
                    b.Navigation("HINH_ANH");

                    b.Navigation("SanPhamMau");
                });
#pragma warning restore 612, 618
        }
    }
}
